apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvvol-3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/mysql
    server: 51.254.227.45
    readOnly: false
